let name="Puja";
school="Shishu Vidya Mandir";
grade="1st";
section="A";
rollno="10";
marks_maths="89";
marks_english="60";
marks_science="90";

 console.log("====================================================");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||        *******  "+school+"  *******    ||");
console.log("||                                                 ||");
console.log("||                   REPORT CARD                   ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||   Name:  "+name+"      Rollno:  "+rollno+"                  ||");
console.log("||                                                 ||");
console.log("||  Grade:  "+grade+"      Section:  "+section+"                   ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||.................................................||");
console.log("||   ... SUBJECT   ...        MARKS        ...     ||");
console.log("||.................................................||");
console.log("||   ...  maths    ...         "+marks_maths+"          ...     ||");
console.log("||   ... English   ...         "+marks_english+"          ...     ||");
console.log("||   ... science   ...         "+marks_science+"          ...     ||");
console.log("||.................................................||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||                :PASS                            ||");
console.log("||                                                 ||");
console.log("||                                                 ||");
console.log("||=================================================||");
